"""AI chat assistant (Chat tab) HTTP surface — see app/coach/assistant.py for the
actual Claude Agent SDK wiring, kept intentionally thin here."""
import json
from datetime import datetime, timezone

from fastapi import APIRouter, BackgroundTasks, HTTPException, Request, Depends

from ..models import SessionLocal, ChatMessage, CoachIssueDraft, User, owned_by
from ..accounts import auth

router = APIRouter()


@router.get("/api/chat/status")
def chat_status():
    from ..coach import assistant
    return {"configured": assistant.is_configured()}


@router.get("/api/chat/history")
def chat_history(user_id: str = Depends(auth.current_user_id)):
    db = SessionLocal()
    try:
        rows = (db.query(ChatMessage)
                .filter(owned_by(ChatMessage.user_id, user_id), ChatMessage.is_test.isnot(True))
                .order_by(ChatMessage.id).all())
        return [{
            "role": r.role, "content": r.content,
            "toolCalls": json.loads(r.tool_calls_json) if r.tool_calls_json else None,
            "charts": json.loads(r.charts_json) if r.charts_json else None,
            "createdAt": r.created_at,
        } for r in rows]
    finally:
        db.close()


def _is_test_request(request: Request) -> bool:
    """Phase 12.1 — set only by my own manual verification traffic against a real
    deployment (X-Hale-Test: 1), never sent by the real browser app. See CLAUDE.md for
    the convention this enforces: any manual chat-endpoint test against production must
    send this header, or it risks polluting real health-note/workout history exactly
    the way an untagged test message once did (see PLAN.md Phase 12's context)."""
    return request.headers.get("x-hale-test") == "1"


@router.post("/api/chat/message")
async def chat_message(request: Request, user_id: str = Depends(auth.current_user_id)):
    body = await request.json()
    message = (body.get("message") or "").strip()
    if not message:
        raise HTTPException(400, "message is required")
    activity_id = body.get("activityId")  # optional — only set by the "Ask coach" button (Phase 26)
    is_test = _is_test_request(request)

    from ..accounts import demo
    db = SessionLocal()
    try:
        if demo.is_demo_user(db, user_id):
            # Never imports assistant.py for a demo user — no Claude Agent SDK client
            # is ever constructed, so a demo session can never burn real API credits.
            reply = demo.mock_chat_reply(message)
            now_iso = datetime.now(timezone.utc).isoformat()
            db.add(ChatMessage(user_id=user_id, role="user", content=message, created_at=now_iso))
            db.add(ChatMessage(user_id=user_id, role="assistant", content=reply, created_at=now_iso))
            db.commit()
            return {"reply": reply, "toolCalls": [], "charts": []}
    finally:
        db.close()

    from ..coach import assistant
    if not assistant.is_configured():
        raise HTTPException(400, "AI assistant not configured — set CLAUDE_CODE_OAUTH_TOKEN or ANTHROPIC_API_KEY")
    try:
        return await assistant.send_message(message, user_id, is_test=is_test, activity_id=activity_id)
    except Exception as e:
        raise HTTPException(500, str(e))


@router.post("/api/chat/reset")
async def chat_reset(user_id: str = Depends(auth.current_user_id)):
    from ..coach import assistant
    db = SessionLocal()
    try:
        db.query(ChatMessage).filter(owned_by(ChatMessage.user_id, user_id)).delete(synchronize_session=False)
        db.commit()
    finally:
        db.close()
    await assistant.reset_client(user_id)
    return {"status": "reset"}


@router.get("/api/coach/personality")
def get_coach_personality(user_id: str = Depends(auth.current_user_id)):
    db = SessionLocal()
    try:
        user = db.get(User, user_id)
        return {"personality": (user.coach_personality if user else None) or "normal"}
    finally:
        db.close()


@router.post("/api/coach/personality")
async def set_coach_personality(request: Request, user_id: str = Depends(auth.current_user_id)):
    from ..coach import assistant
    from ..coach import core as coach
    body = await request.json()
    personality = body.get("personality")
    if personality not in coach.VALID_PERSONAS:
        raise HTTPException(400, f"personality must be one of {coach.VALID_PERSONAS}")
    db = SessionLocal()
    try:
        user = db.get(User, user_id)
        if user:
            user.coach_personality = personality
            db.commit()
    finally:
        db.close()
    # Persona is baked into the SDK's system prompt at client-construction time, not
    # re-read per message — reset so the next chat message rebuilds it with the new tone.
    await assistant.reset_client(user_id)
    return {"personality": personality}


# ---------- Daily coach report (Phase 27) — a rolling trailing-7-day check-in,
# pre-generated by a nightly cron job (main.py, 04:45 APP_TIMEZONE) and cached in
# sync_meta, date-keyed via local_today so each calendar day gets fresh content.
# GET here is a PURE cache read — it never runs the LLM call in a request's response
# path (Phase 27.1: the original lazy-generate-on-first-load design made the first
# Home load of the day visibly stall for several seconds, real feedback from using
# it). On a cache miss (the cron hasn't run yet today — e.g. the container wasn't up
# at 04:45, or this is a brand new user), it fires a background task to generate and
# cache the report without the caller ever waiting on it, returning "no report yet"
# immediately; a later request that same day will see it once the background task
# finishes. ----------
_REPORT_GENERATING_SENTINEL = "\x00generating\x00"  # distinct from "" (tried, got nothing)


@router.get("/api/coach/daily-report")
def daily_coach_report(background_tasks: BackgroundTasks, user_id: str = Depends(auth.current_user_id)):
    from ..util import local_today
    from ..models import get_sync_meta, set_sync_meta, user_key
    today = local_today(user_id).isoformat()
    cache_key = user_key(user_id, f"coach_report_{today}")
    cached = get_sync_meta(cache_key)
    if cached is not None:
        # "" means a prior attempt today already tried and got nothing (not
        # configured, or the LLM call failed/looked untrustworthy) — cached too, so
        # a bad day doesn't retry the LLM call on every subsequent page load, only
        # on the next calendar day. The generating sentinel means a background task
        # from an earlier request this same window is already in flight.
        if cached == _REPORT_GENERATING_SENTINEL:
            return {"report": None, "date": today}
        return {"report": cached or None, "date": today}

    # Cache miss and nothing in flight — write the sentinel synchronously (cheap,
    # plain key/value write) so a second fast page reload before the background task
    # finishes doesn't also kick off a redundant LLM call, then hand off the actual
    # generation to run after this response is sent.
    set_sync_meta(cache_key, _REPORT_GENERATING_SENTINEL)

    async def _generate():
        from ..coach import daily_report
        await daily_report.generate_and_cache(user_id)

    background_tasks.add_task(_generate)
    return {"report": None, "date": today}


# ---------- Coach self-review draft (Phase 12.5) — one rolling draft GitHub issue per
# user, accumulated by coach/self_review.py's periodic job and the live
# log_product_feedback chat tool. Draft-only: never posted to github.com from here,
# see CLAUDE.md. Fetched via GET, refreshed on-demand via POST /refresh (e.g. when the
# user opens the Preview dialog — see SettingsPage.tsx), cleared via POST /clear once
# pulled/published elsewhere. ----------
def _draft_to_dict(draft: CoachIssueDraft | None):
    if not draft or not draft.body_markdown:
        return None
    return {
        "title": draft.title, "body": draft.body_markdown,
        "frustrationCount": draft.frustration_count or 0, "updatedAt": draft.updated_at,
    }


@router.get("/api/coach-issue")
def get_coach_issue(user_id: str = Depends(auth.current_user_id)):
    db = SessionLocal()
    try:
        return _draft_to_dict(db.get(CoachIssueDraft, user_id))
    finally:
        db.close()


@router.post("/api/coach-issue/refresh")
def refresh_coach_issue(user_id: str = Depends(auth.current_user_id)):
    """On-demand incremental review — reuses the exact same run_for_user the daily
    scheduled job calls, so a click here never duplicates or re-reviews anything the
    daily job already covered. Cheap when there's nothing new: run_for_user's own
    checkpoint check short-circuits before any LLM call if no messages have landed
    since the last review (scheduled or on-demand)."""
    from ..coach import self_review
    db = SessionLocal()
    try:
        self_review.run_for_user(db, user_id)
        return _draft_to_dict(db.get(CoachIssueDraft, user_id))
    finally:
        db.close()


@router.post("/api/coach-issue/clear")
def clear_coach_issue(user_id: str = Depends(auth.current_user_id)):
    db = SessionLocal()
    try:
        draft = db.get(CoachIssueDraft, user_id)
        if draft:
            db.delete(draft)
            db.commit()
        return {"cleared": True}
    finally:
        db.close()
